# Generated by Django 5.2.3 on 2025-08-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Therapy Now', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSpreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensation_sales_sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_transaction_sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_report_sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_transaction_sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clinic')),
            ],
            options={
                'verbose_name_plural': 'Clinic Sheets',
            },
        ),
    ]
