# Generated by Django 5.2.3 on 2025-08-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clinic_userspreadsheet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSpreadsheet',
            new_name='ClinicSpreadsheet',
        ),
    ]
