# Generated by Django 5.2.3 on 2025-08-15 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clinic_address_clinic_created_at_clinic_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicspreadsheet',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.clinic'),
        ),
    ]
