# Generated by Django 5.2.3 on 2025-08-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_clinicspreadsheet_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicspreadsheet',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to='api.clinic'),
        ),
    ]
