# Generated by Django 5.2.3 on 2025-08-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clinicspreadsheet_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicspreadsheet',
            name='merge_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
