# Generated by Django 5.2.3 on 2025-08-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicspreadsheet',
            name='time_hour_sheet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
