# Generated by Django 5.2.3 on 2025-08-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_clinicspreadsheet_time_hour_sheet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='gst',
            new_name='federal_income_tax',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='pst',
            new_name='provincial_income_tax',
        ),
    ]
