# Generated by Django 5.2.3 on 2025-08-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_gst_sitesettings_federal_income_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='federal_income_tax',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='provincial_income_tax',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='federal_tax_brackets',
            field=models.JSONField(default=list, help_text='Federal income tax brackets'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='provincial_tax_brackets',
            field=models.JSONField(default=list, help_text='Provincial income tax brackets'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cpp',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ei_ee',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ei_er',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
