# Generated by Django 5.2.3 on 2025-08-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_sitesettings_federal_income_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cpp_cap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cpp_exemption',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
