# Generated by Django 5.2.3 on 2025-08-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sitesettings_cpp_cap_sitesettings_cpp_exemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ei_cap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
