# Generated by Django 5.2.3 on 2025-08-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sitesettings_ei_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='overtime_pay_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacation_pay_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
