# Generated by Django 5.2.3 on 2025-08-26 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sitesettings_overtime_pay_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('subtotal_income', models.DecimalField(decimal_places=3, max_digits=8)),
                ('vacation_pay', models.DecimalField(decimal_places=3, max_digits=8)),
                ('overtime_pay', models.DecimalField(decimal_places=3, max_digits=8)),
                ('revenue_share_income', models.DecimalField(decimal_places=3, max_digits=8)),
                ('gst', models.DecimalField(decimal_places=3, max_digits=8)),
                ('total_income', models.DecimalField(decimal_places=3, max_digits=8)),
                ('commission_deduction', models.DecimalField(decimal_places=3, max_digits=8)),
                ('pos_fees', models.DecimalField(decimal_places=3, max_digits=8)),
                ('provincial_income_tax', models.DecimalField(decimal_places=3, max_digits=8)),
                ('federal_income_tax', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cpp_contrib', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ei_contrib', models.DecimalField(decimal_places=3, max_digits=8)),
                ('rent', models.DecimalField(decimal_places=3, max_digits=10)),
                ('revenue_share_deduction', models.DecimalField(decimal_places=3, max_digits=8)),
                ('revenue_share_deduction_payee', models.DecimalField(decimal_places=3, max_digits=8)),
                ('total_deductions', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('payroll_number', models.CharField(max_length=50, unique=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
