# Generated by Django 5.2.3 on 2025-08-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_payrollrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecords',
            name='hours_worked',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrecords',
            name='role_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollrecords',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
