# Generated by Django 5.2.3 on 2025-08-26 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_payrollrecords_hours_worked_payrollrecords_role_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrecords',
            name='revenue_share_deduction_payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_share_deduction_payee_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
