# Generated by Django 5.2.3 on 2025-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_payrollrecords_revenue_share_deduction_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrecords',
            name='revenue_share_deduction_payee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
