# Generated by Django 5.2.3 on 2025-08-26 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_payrollrecords_revenue_share_deduction_payee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueShareContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_contributed', models.DecimalField(decimal_places=3, max_digits=8)),
                ('contribution_type', models.CharField(choices=[('specific_user', 'From Specific User'), ('student_share', 'From Student Revenue Share')], max_length=50)),
                ('contributing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payrollrecords')),
            ],
        ),
        migrations.AddField(
            model_name='payrollrecords',
            name='revenue_share_income_payers',
            field=models.ManyToManyField(blank=True, related_name='revenue_share_income_payers_set', through='api.RevenueShareContribution', to=settings.AUTH_USER_MODEL),
        ),
    ]
