# Generated by Django 5.2.3 on 2025-08-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_revenuesharecontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cpp_er',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
