# Generated by Django 5.2.3 on 2025-08-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_sitesettings_cpp_er'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='cpp_er',
        ),
    ]
