# Generated by Django 5.2.3 on 2025-08-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_sitesettings_cpp_er'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecords',
            name='net_payment',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollrecords',
            name='total_income',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
