# Generated by Django 5.2.3 on 2025-08-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_payrollrecords_net_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SheetColumnPreference',
        ),
    ]
