# Generated by Django 5.2.3 on 2025-08-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_sheetcolumnpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecords',
            name='cpp_er',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrecords',
            name='ei_er',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
