# Generated by Django 5.2.3 on 2025-08-12 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPaymentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PrimaryPaymentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_dates', models.JSONField(default=list)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HasRent',
            fields=[
                ('additionalpaymentrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.additionalpaymentrole')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('registration.additionalpaymentrole',),
        ),
        migrations.CreateModel(
            name='ProfitSharing',
            fields=[
                ('additionalpaymentrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.additionalpaymentrole')),
                ('sharing_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('registration.additionalpaymentrole',),
        ),
        migrations.CreateModel(
            name='CommissionContractor',
            fields=[
                ('primarypaymentrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.primarypaymentrole')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('registration.primarypaymentrole',),
        ),
        migrations.CreateModel(
            name='CommissionEmployee',
            fields=[
                ('primarypaymentrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.primarypaymentrole')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('registration.primarypaymentrole',),
        ),
        migrations.CreateModel(
            name='HourlyContractor',
            fields=[
                ('primarypaymentrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.primarypaymentrole')),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('registration.primarypaymentrole',),
        ),
        migrations.CreateModel(
            name='HourlyEmployee',
            fields=[
                ('primarypaymentrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.primarypaymentrole')),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('registration.primarypaymentrole',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='primarypaymentrole',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='registration.userprofile'),
        ),
        migrations.AddField(
            model_name='additionalpaymentrole',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_roles', to='registration.userprofile'),
        ),
        migrations.CreateModel(
            name='RevenueSharing',
            fields=[
                ('additionalpaymentrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.additionalpaymentrole')),
                ('sharing_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_sharing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('registration.additionalpaymentrole',),
        ),
    ]
