# Generated by Django 5.2.3 on 2025-08-13 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalpaymentrole',
            options={},
        ),
        migrations.AlterField(
            model_name='revenuesharing',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_sharing_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='additionalpaymentrole',
            unique_together={('user_profile', 'polymorphic_ctype')},
        ),
    ]
