# Generated by Django 5.2.3 on 2025-08-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_additionalpaymentrole_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalpaymentrole',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterUniqueTogether(
            name='additionalpaymentrole',
            unique_together=set(),
        ),
    ]
