# Generated by Django 5.2.3 on 2025-08-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_additionalpaymentrole_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.DecimalField(decimal_places=4, max_digits=8)),
                ('pst', models.DecimalField(decimal_places=4, max_digits=8)),
                ('cpp', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ei_ee', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ei_er', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
    ]
