# Generated by Django 5.2.3 on 2025-08-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
