# Generated by Django 5.2.3 on 2025-08-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_delete_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ytd_pay',
            field=models.FloatField(default=0.0),
        ),
    ]
