# Generated by Django 5.2.3 on 2025-08-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_userprofile_ytd_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ytd_deduction',
            field=models.FloatField(default=0.0),
        ),
    ]
