# Generated by Django 5.2.3 on 2025-08-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_userprofile_ytd_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpp_contrib',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ei_contrib',
            field=models.FloatField(default=0.0),
        ),
    ]
