# Generated by Django 5.2.3 on 2025-08-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_userprofile_cpp_contrib_userprofile_ei_contrib'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarypaymentrole',
            name='payment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('semi-monthly', 'Semi-monthly'), ('monthly', 'Monthly')], default='bi-weekly', max_length=20),
        ),
    ]
