# Generated by Django 5.2.3 on 2025-08-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_primarypaymentrole_payment_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarypaymentrole',
            name='payment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('semi-monthly', 'Semi-monthly'), ('monthly', 'Monthly')], default='semi-monthly', max_length=20),
        ),
    ]
