# Generated by Django 5.2.3 on 2025-08-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_primarypaymentrole_payment_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarypaymentrole',
            name='payroll_dates',
        ),
    ]
