# Generated by Django 5.2.3 on 2025-08-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_remove_primarypaymentrole_payroll_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('primarypaymentrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.primarypaymentrole')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('registration.primarypaymentrole',),
        ),
    ]
