# Generated by Django 5.2.3 on 2025-08-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuesharing',
            name='target_type',
            field=models.CharField(choices=[('specific_user', 'Specific User'), ('all_students', 'All Students')], default='specific_user', max_length=20),
        ),
    ]
