# Generated by Django 5.2.3 on 2025-08-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_revenuesharing_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasrent',
            name='rent_description',
            field=models.TextField(blank=True),
        ),
    ]
