# Generated by Django 5.2.3 on 2025-08-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_hasrent_rent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasrent',
            name='rent_description',
        ),
    ]
