# Generated by Django 5.2.3 on 2025-08-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_remove_hasrent_rent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contrib_year',
            field=models.IntegerField(default=2025),
        ),
    ]
