# Generated by Django 5.2.3 on 2025-07-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_desk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
