# Generated by Django 5.2.3 on 2025-08-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_desk', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersheet',
            name='merge_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
